/**
 * Metro resolves an imported media file to an entry in the asset registry, which is
 * an opaque handle rather than a path — the same import yields a bundled resource on
 * Android and a URL in the web export.
 *
 * Declared here rather than relied on from `expo-env.d.ts`: that file is generated by
 * the Expo CLI and is gitignored, so a fresh clone would fail `npm run typecheck`
 * before anyone had run `expo start`.
 */
declare module '*.wav' {
  const asset: number;
  export default asset;
}
