/**
 * Re-embed the brand artwork into `src/ui/geaLogo.ts` from the files in `assets/`.
 *
 *     node scripts/embed-logo.mjs
 *
 * This is the step to run when you have the REAL logo. Drop it in as:
 *
 *     assets/gea-logo.png   the full lockup, letters + "Engineering for a better world."
 *     assets/gea-mark.png   the letters alone (used on the rockets, where the tagline
 *                           would render as a 4px smudge)
 *
 * ...then run this and re-export the web build. Nothing else changes: the aspect
 * ratios are measured from the files themselves, so a differently-proportioned logo
 * lays out correctly without touching a component.
 *
 * `gen-logo.mjs` is the fallback that DRAWS an approximation when no real asset is
 * available. It is not the source of truth — this is.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const assets = path.resolve(here, '../assets');
const out = path.resolve(here, '../src/ui/geaLogo.ts');

/** Width and height straight out of a PNG's IHDR chunk — no image library needed. */
function pngSize(buf) {
  if (buf.subarray(0, 8).toString('latin1') !== '\x89PNG\r\n\x1a\n') {
    throw new Error('not a PNG (the embedder only handles PNG)');
  }
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

const files = { logo: 'gea-logo.png', mark: 'gea-mark.png' };
for (const f of Object.values(files)) {
  if (!existsSync(path.join(assets, f))) throw new Error(`missing assets/${f}`);
}

const logo = readFileSync(path.join(assets, files.logo));
const mark = readFileSync(path.join(assets, files.mark));
const logoSize = pngSize(logo);
const markSize = pngSize(mark);

const wrap = (b64) =>
  b64
    .match(/.{1,100}/g)
    .map((c) => `  '${c}'`)
    .join(' +\n');

const source = `/**
 * The GEA artwork, as data URIs.
 *
 * GENERATED by \`scripts/embed-logo.mjs\` from \`assets/gea-logo.png\` and
 * \`assets/gea-mark.png\`. Do not edit by hand — replace those files and re-run it.
 *
 * Inlined rather than loaded from assets/ on purpose. The web build is a STATIC export
 * served under a \`/app\` base URL (app.json -> experiments.baseUrl) and the native
 * build resolves assets through Metro; a data URI is the one form that cannot break on
 * either, and it needs no round trip.
 *
 * Two of them, because one drawing does not serve both jobs. The LOCKUP carries the
 * tagline and is used wherever it can actually be read. The MARK is the letters alone,
 * for the places where the tagline would be illegible rather than absent - the nav
 * bar's right edge, and the rockets, whose bodies are 92px wide.
 */

/** Measured from the artwork, so callers only ever pick a width and a differently
 *  proportioned logo lays out correctly without a component change. */
export const GEA_LOGO_ASPECT = ${logoSize.width} / ${logoSize.height};
export const GEA_MARK_ASPECT = ${markSize.width} / ${markSize.height};

export const GEA_BLUE = '#1414C8';

/** The letters plus "Engineering for a better world." */
export const GEA_LOGO_URI =
  'data:image/png;base64,' +
${wrap(logo.toString('base64'))};

/** The letters alone, without the tagline. */
export const GEA_MARK_URI =
  'data:image/png;base64,' +
${wrap(mark.toString('base64'))};
`;

writeFileSync(out, source);
console.log(
  `embedded  lockup ${logoSize.width}x${logoSize.height} (${logo.length} bytes)  ` +
    `mark ${markSize.width}x${markSize.height} (${mark.length} bytes)`,
);
