import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';
import scanBeep from '../../assets/sounds/scan-beep.wav';
import cylinderClang from '../../assets/sounds/cylinder-clang.wav';

/**
 * The app's two sound cues.
 *
 * ## Why sound at all
 *
 * Both cues answer the same question — "did that register?" — for a person who is
 * not looking at the screen. A stores manager scanning forty cylinders is looking at
 * the cylinders, and a driver watching a submission go in is looking at the driver.
 * The visual feedback stays exactly as it was; the sound is an addition to it, never
 * a replacement, because a phone can be muted and a yard can be loud.
 *
 * That is also why nothing here is allowed to fail loudly. Every entry point is
 * fire-and-forget and swallows its errors: a muted phone, a browser that has not
 * granted audio yet, or an asset that failed to decode must never be the reason a
 * scan is lost.
 *
 * ## One code path, both targets
 *
 * `expo-audio` ships a web implementation as well as a native one, so this module
 * deliberately does NOT branch on `Platform.OS` — the same players, fed the same two
 * WAV files, run in the browser and in the APK. See docs/WEB_PARITY.md: every branch
 * avoided is a class of drift that cannot happen.
 *
 * The one genuine difference is browser autoplay policy, which refuses audio until
 * the page has seen a user gesture. `primeSounds()` exists for that, and is called
 * from the dashboard on the tap that starts a workflow — long before the first scan.
 * On the device it is a harmless no-op.
 */
export type Cue = 'scan' | 'clang';

/** The files are generated by `scripts/gen-sounds.mjs`; see it for how each is made. */
const SOURCES: Record<Cue, number> = { scan: scanBeep, clang: cylinderClang };

const players: Partial<Record<Cue, AudioPlayer>> = {};
let audioModeSet = false;

function playerFor(cue: Cue): AudioPlayer | null {
  const existing = players[cue];
  if (existing) return existing;
  try {
    if (!audioModeSet) {
      audioModeSet = true;
      // A field phone spends its life on silent. The cues are confirmations of work
      // being recorded, so they are worth hearing anyway.
      void setAudioModeAsync({ playsInSilentMode: true }).catch(() => {});
    }
    const player = createAudioPlayer(SOURCES[cue]);
    players[cue] = player;
    return player;
  } catch {
    return null;
  }
}

/**
 * Play a cue, now, interrupting itself if it is still ringing.
 *
 * The rewind is what makes rapid scanning work: `play()` on a player that has already
 * reached the end of its clip does nothing at all, so the second cylinder of a batch
 * would be silent without it.
 */
export function playCue(cue: Cue): void {
  const player = playerFor(cue);
  if (!player) return;
  try {
    void Promise.resolve(player.seekTo(0))
      .then(() => player.play())
      .catch(() => {});
  } catch {
    // A player disposed underneath us, or a browser refusing to start audio. Neither
    // is worth surfacing — the visual feedback has already told the user what
    // happened.
  }
}

/**
 * Create both players ahead of the first cue, from inside a real user gesture.
 *
 * Called on the dashboard tile press. Two things come of it: the clips are fetched
 * and decoded before anything needs them, so the first beep is not late; and the
 * players are constructed while the page has user activation, which is what a
 * browser wants to see before it will let audio start at all. The scan that fires
 * the first beep comes from a camera callback, which does not count as one.
 *
 * It deliberately does NOT play-then-pause to "unlock" the audio, which is the usual
 * trick: on the web that aborts the play promise and surfaces as an uncaught
 * `The play() request was interrupted by a call to pause()`. Sticky activation from
 * the tap already covers the case, so the noise buys nothing.
 */
export function primeSounds(): void {
  for (const cue of ['scan', 'clang'] as const) playerFor(cue);
}
